export {
  getAboutHighlights,
  getCurrentEmployers,
  getOverviewRoles,
  profile,
  type AboutHighlight,
  type Certificate,
  type Education,
  type ExperienceRole,
  type ExpertiseArea,
  type Language,
  type NavItem,
  type OverviewRole,
  type Profile,
} from "@/content/profile";
